### ISSUE TITLE
add support for JWT based authentication for mobile applications

### ISSUE THREAD

**Issue by yawetse** [typesettin/periodicjs.ext.oauth2server#1]
https://stormpath.com/blog/the-ultimate-guide-to-mobile-api-security/

**Comment by yawetse** [comment]
![image](https://cloud.githubusercontent.com/assets/1192414/12934043/b471cf40-cf59-11e5-83c3-2bda1193f85d.png)

**Comment by ecasilla** [comment]
Is it going to support both auth protocols JWT and oauth ?

**Comment by yawetse** [comment]
Both, it's going to turn any periodic app into an oauth server: http://scottksmith.com/blog/2014/07/02/beer-locker-building-a-restful-api-with-node-oauth2-server/

Jan and I will make another extension that will turn all models into restful Api endpoints

**Comment by yawetse** [comment]
* http://scottksmith.com/blog/2014/07/02/beer-locker-building-a-restful-api-with-node-oauth2-server/
* https://github.com/jaredhanson/oauth2orize
* https://github.com/coolaj86/example-oauth2orize-consumer/blob/master/server.js

**Comment by yawetse** [comment]
const crypto = require('crypto');
crypto.pbkdf2('secret', 'salt', 10, 16, 'sha512', (err, key) => {
  if (err) throw err;
  console.log(key.toString('hex'));  // 'c5e478d...1469e50'
});

console.log(crypto.randomBytes(16).toString('base64'));

**Comment by yawetse** [comment]
http://www.sitepoint.com/using-json-web-tokens-node-js/
